/*
 * Copyright 2025 New Vector Ltd.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
 * Please see LICENSE files in the repository root for full details.
 */

/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.LightHcColorTokens

/**
 * Semantic colors for the high contrast light Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcLight = SemanticColors(
    bgAccentHovered = LightHcColorTokens.colorBlue1000,
    bgAccentPressed = LightHcColorTokens.colorBlue1100,
    bgAccentRest = LightHcColorTokens.colorBlue900,
    bgAccentSelected = LightHcColorTokens.colorBlue300,
    bgActionPrimaryDisabled = LightHcColorTokens.colorBlue900,
    bgActionPrimaryHovered = LightHcColorTokens.colorBlue1100,
    bgActionPrimaryPressed = LightHcColorTokens.colorBlue1000,
    bgActionPrimaryRest = LightHcColorTokens.colorBlue1200,
    bgActionSecondaryHovered = LightHcColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = LightHcColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = LightHcColorTokens.colorThemeBg,
    bgBadgeAccent = LightHcColorTokens.colorAlphaGreen400,
    bgBadgeDefault = LightHcColorTokens.colorAlphaGray400,
    bgBadgeInfo = LightHcColorTokens.colorAlphaBlue400,
    bgCanvasDefault = LightHcColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = LightHcColorTokens.colorThemeBg,
    bgCanvasDisabled = LightHcColorTokens.colorGray200,
    bgCriticalHovered = LightHcColorTokens.colorRed1000,
    bgCriticalPrimary = LightHcColorTokens.colorRed900,
    bgCriticalSubtle = LightHcColorTokens.colorRed200,
    bgCriticalSubtleHovered = LightHcColorTokens.colorRed300,
    bgDecorative1 = LightHcColorTokens.colorLime300,
    bgDecorative2 = LightHcColorTokens.colorCyan300,
    bgDecorative3 = LightHcColorTokens.colorFuchsia300,
    bgDecorative4 = LightHcColorTokens.colorPurple300,
    bgDecorative5 = LightHcColorTokens.colorPink300,
    bgDecorative6 = LightHcColorTokens.colorOrange300,
    bgInfoSubtle = LightHcColorTokens.colorBlue200,
    bgSubtlePrimary = LightHcColorTokens.colorBlue400,
    bgSubtleSecondary = LightHcColorTokens.colorGray300,
    bgSubtleSecondaryLevel0 = LightHcColorTokens.colorGray300,
    bgSuccessSubtle = LightHcColorTokens.colorGreen200,
    borderAccentSubtle = LightHcColorTokens.colorBlue700,
    borderCriticalHovered = LightHcColorTokens.colorRed1000,
    borderCriticalPrimary = LightHcColorTokens.colorRed900,
    borderCriticalSubtle = LightHcColorTokens.colorRed500,
    borderDisabled = LightHcColorTokens.colorGray500,
    borderFocused = LightHcColorTokens.colorBlue900,
    borderInfoSubtle = LightHcColorTokens.colorBlue700,
    borderInteractiveHovered = LightHcColorTokens.colorGray1100,
    borderInteractivePrimary = LightHcColorTokens.colorGray800,
    borderInteractiveSecondary = LightHcColorTokens.colorGray600,
    borderSuccessSubtle = LightHcColorTokens.colorGreen500,
    gradientActionStop1 = LightHcColorTokens.colorGreen500,
    gradientActionStop2 = LightHcColorTokens.colorGreen700,
    gradientActionStop3 = LightHcColorTokens.colorGreen900,
    gradientActionStop4 = LightHcColorTokens.colorGreen1100,
    gradientInfoStop1 = LightHcColorTokens.colorAlphaBlue500,
    gradientInfoStop2 = LightHcColorTokens.colorAlphaBlue400,
    gradientInfoStop3 = LightHcColorTokens.colorAlphaBlue300,
    gradientInfoStop4 = LightHcColorTokens.colorAlphaBlue200,
    gradientInfoStop5 = LightHcColorTokens.colorAlphaBlue100,
    gradientInfoStop6 = LightHcColorTokens.colorTransparent,
    gradientSubtleStop1 = LightHcColorTokens.colorThemeBg,
    gradientSubtleStop2 = LightHcColorTokens.colorThemeBg,
    gradientSubtleStop3 = LightHcColorTokens.colorThemeBg,
    gradientSubtleStop4 = LightHcColorTokens.colorThemeBg,
    gradientSubtleStop5 = LightHcColorTokens.colorThemeBg,
    gradientSubtleStop6 = LightHcColorTokens.colorThemeBg,
    iconAccentPrimary = LightHcColorTokens.colorBlue1400,
    iconAccentTertiary = LightHcColorTokens.colorBlue1200,
    iconCriticalPrimary = LightHcColorTokens.colorRed900,
    iconDisabled = LightHcColorTokens.colorGray700,
    iconInfoPrimary = LightHcColorTokens.colorBlue900,
    iconOnSolidPrimary = LightHcColorTokens.colorThemeBg,
    iconPrimary = LightHcColorTokens.colorGray1400,
    iconPrimaryAlpha = LightHcColorTokens.colorAlphaGray1400,
    iconQuaternary = LightHcColorTokens.colorGray700,
    iconQuaternaryAlpha = LightHcColorTokens.colorAlphaGray700,
    iconSecondary = LightHcColorTokens.colorGray900,
    iconSecondaryAlpha = LightHcColorTokens.colorAlphaGray900,
    iconSuccessPrimary = LightHcColorTokens.colorBlue1200,
    iconTertiary = LightHcColorTokens.colorGray800,
    iconTertiaryAlpha = LightHcColorTokens.colorAlphaGray800,
    textActionAccent = LightHcColorTokens.colorBlue1200,
    textActionPrimary = LightHcColorTokens.colorGray1400,
    textBadgeAccent = LightHcColorTokens.colorGreen1100,
    textBadgeInfo = LightHcColorTokens.colorBlue1100,
    textCriticalPrimary = LightHcColorTokens.colorRed900,
    textDecorative1 = LightHcColorTokens.colorLime1100,
    textDecorative2 = LightHcColorTokens.colorCyan1100,
    textDecorative3 = LightHcColorTokens.colorFuchsia1100,
    textDecorative4 = LightHcColorTokens.colorPurple1100,
    textDecorative5 = LightHcColorTokens.colorPink1100,
    textDecorative6 = LightHcColorTokens.colorOrange1100,
    textDisabled = LightHcColorTokens.colorGray800,
    textInfoPrimary = LightHcColorTokens.colorBlue1100,
    textLinkExternal = LightHcColorTokens.colorBlue1100,
    textOnSolidPrimary = LightHcColorTokens.colorThemeBg,
    textPrimary = LightHcColorTokens.colorGray1400,
    textSecondary = LightHcColorTokens.colorGray900,
    textSuccessPrimary = LightHcColorTokens.colorGreen900,
    isLight = true,
)
