
//
// CompoundColorTokens.swift
//

import SwiftUI

public class CompoundColorTokens {
    public let bgAccentHovered = Color("bgAccentHovered", bundle: Bundle.module)
    public let bgAccentPressed = Color("bgAccentPressed", bundle: Bundle.module)
    public let bgAccentRest = Color("bgAccentRest", bundle: Bundle.module)
    public let bgAccentSelected = Color("bgAccentSelected", bundle: Bundle.module)
    public let bgAccentSubtle = CompoundCoreColorTokens.green200
    public let bgActionPrimaryDisabled = Color("bgActionPrimaryDisabled", bundle: Bundle.module)
    public let bgActionPrimaryHovered = Color("bgActionPrimaryHovered", bundle: Bundle.module)
    public let bgActionPrimaryPressed = Color("bgActionPrimaryPressed", bundle: Bundle.module)
    public let bgActionPrimaryRest = Color("bgActionPrimaryRest", bundle: Bundle.module)
    public let bgActionSecondaryHovered = Color("bgActionSecondaryHovered", bundle: Bundle.module)
    public let bgActionSecondaryPressed = Color("bgActionSecondaryPressed", bundle: Bundle.module)
    public let bgActionSecondaryRest = Color("bgActionSecondaryRest", bundle: Bundle.module)
    public let bgActionTertiaryHovered = CompoundCoreColorTokens.gray300
    public let bgActionTertiaryRest = CompoundCoreColorTokens.themeBg
    public let bgActionTertiarySelected = CompoundCoreColorTokens.gray400
    public let bgBadgeAccent = Color("bgBadgeAccent", bundle: Bundle.module)
    public let bgBadgeCritical = Color("bgBadgeCritical", bundle: Bundle.module)
    public let bgBadgeDefault = Color("bgBadgeDefault", bundle: Bundle.module)
    public let bgBadgeInfo = Color("bgBadgeInfo", bundle: Bundle.module)
    public let bgBadgePrimary = Color("bgBadgePrimary", bundle: Bundle.module)
    public let bgBadgeSecondary = Color("bgBadgeSecondary", bundle: Bundle.module)
    public let bgBadgeSuccess = Color("bgBadgeSuccess", bundle: Bundle.module)
    public let bgBadgeWarning = Color("bgBadgeWarning", bundle: Bundle.module)
    public let bgCanvasDefault = CompoundCoreColorTokens.themeBg
    public let bgCanvasDefaultLevel1 = Color("bgCanvasDefaultLevel1", bundle: Bundle.module)
    public let bgCanvasDisabled = CompoundCoreColorTokens.gray200
    public let bgCriticalHovered = Color("bgCriticalHovered", bundle: Bundle.module)
    public let bgCriticalPrimary = Color("bgCriticalPrimary", bundle: Bundle.module)
    public let bgCriticalSubtle = Color("bgCriticalSubtle", bundle: Bundle.module)
    public let bgCriticalSubtleHovered = Color("bgCriticalSubtleHovered", bundle: Bundle.module)
    public let bgDecorative1 = CompoundCoreColorTokens.green300
    public let bgDecorative2 = CompoundCoreColorTokens.cyan300
    public let bgDecorative3 = CompoundCoreColorTokens.fuchsia300
    public let bgDecorative4 = CompoundCoreColorTokens.purple300
    public let bgDecorative5 = CompoundCoreColorTokens.pink300
    public let bgDecorative6 = CompoundCoreColorTokens.orange300
    public let bgInfoSubtle = CompoundCoreColorTokens.blue200
    public let bgSubtlePrimary = Color("bgSubtlePrimary", bundle: Bundle.module)
    public let bgSubtleSecondary = Color("bgSubtleSecondary", bundle: Bundle.module)
    public let bgSubtleSecondaryLevel0 = Color("bgSubtleSecondaryLevel0", bundle: Bundle.module)
    public let bgSubtleTertiary = CompoundCoreColorTokens.gray100
    public let bgSuccessHovered = CompoundCoreColorTokens.green1000
    public let bgSuccessPressed = CompoundCoreColorTokens.green1100
    public let bgSuccessRest = CompoundCoreColorTokens.green900
    public let bgSuccessSubtle = CompoundCoreColorTokens.green400
    public let borderAccentPrimary = CompoundCoreColorTokens.green900
    public let borderAccentSubtle = CompoundCoreColorTokens.blue700
    public let borderCriticalHovered = CompoundCoreColorTokens.red1000
    public let borderCriticalPrimary = CompoundCoreColorTokens.red900
    public let borderCriticalSubtle = CompoundCoreColorTokens.red400
    public let borderDisabled = CompoundCoreColorTokens.gray500
    public let borderFocused = CompoundCoreColorTokens.blue500
    public let borderInfoSubtle = CompoundCoreColorTokens.blue700
    public let borderInteractiveHovered = CompoundCoreColorTokens.gray1100
    public let borderInteractivePrimary = CompoundCoreColorTokens.gray800
    public let borderInteractiveSecondary = CompoundCoreColorTokens.gray600
    public let borderSuccessPrimary = CompoundCoreColorTokens.green900
    public let borderSuccessSubtle = CompoundCoreColorTokens.green500
    public let gradientActionStop1 = Color("gradientActionStop1", bundle: Bundle.module)
    public let gradientActionStop2 = Color("gradientActionStop2", bundle: Bundle.module)
    public let gradientActionStop3 = Color("gradientActionStop3", bundle: Bundle.module)
    public let gradientActionStop4 = Color("gradientActionStop4", bundle: Bundle.module)
    public let gradientCriticalStop1 = Color("gradientCriticalStop1", bundle: Bundle.module)
    public let gradientCriticalStop2 = Color("gradientCriticalStop2", bundle: Bundle.module)
    public let gradientInfoStop1 = Color("gradientInfoStop1", bundle: Bundle.module)
    public let gradientInfoStop2 = Color("gradientInfoStop2", bundle: Bundle.module)
    public let gradientSubtleStop1 = Color("gradientSubtleStop1", bundle: Bundle.module)
    public let gradientSubtleStop2 = Color("gradientSubtleStop2", bundle: Bundle.module)
    public let gradientSubtleStop3 = Color("gradientSubtleStop3", bundle: Bundle.module)
    public let gradientSubtleStop4 = Color("gradientSubtleStop4", bundle: Bundle.module)
    public let gradientSubtleStop5 = Color("gradientSubtleStop5", bundle: Bundle.module)
    public let gradientSubtleStop6 = Color("gradientSubtleStop6", bundle: Bundle.module)
    public let iconAccentPrimary = Color("iconAccentPrimary", bundle: Bundle.module)
    public let iconAccentTertiary = Color("iconAccentTertiary", bundle: Bundle.module)
    public let iconBadgeAccent = Color("iconBadgeAccent", bundle: Bundle.module)
    public let iconBadgeCritical = Color("iconBadgeCritical", bundle: Bundle.module)
    public let iconBadgeDefault = Color("iconBadgeDefault", bundle: Bundle.module)
    public let iconBadgeExternal = CompoundCoreColorTokens.orange1200
    public let iconBadgeInfo = Color("iconBadgeInfo", bundle: Bundle.module)
    public let iconBadgePrimary = Color("iconBadgePrimary", bundle: Bundle.module)
    public let iconBadgeSecondary = Color("iconBadgeSecondary", bundle: Bundle.module)
    public let iconBadgeSuccess = Color("iconBadgeSuccess", bundle: Bundle.module)
    public let iconBadgeWarning = Color("iconBadgeWarning", bundle: Bundle.module)
    public let iconCriticalPrimary = Color("iconCriticalPrimary", bundle: Bundle.module)
    public let iconDisabled = Color("iconDisabled", bundle: Bundle.module)
    public let iconInfoPrimary = Color("iconInfoPrimary", bundle: Bundle.module)
    public let iconOnSolidPrimary = Color("iconOnSolidPrimary", bundle: Bundle.module)
    public let iconPrimary = Color("iconPrimary", bundle: Bundle.module)
    public let iconPrimaryAlpha = Color("iconPrimaryAlpha", bundle: Bundle.module)
    public let iconQuaternary = Color("iconQuaternary", bundle: Bundle.module)
    public let iconQuaternaryAlpha = Color("iconQuaternaryAlpha", bundle: Bundle.module)
    public let iconSecondary = Color("iconSecondary", bundle: Bundle.module)
    public let iconSecondaryAlpha = Color("iconSecondaryAlpha", bundle: Bundle.module)
    public let iconSuccessPrimary = Color("iconSuccessPrimary", bundle: Bundle.module)
    public let iconTertiary = Color("iconTertiary", bundle: Bundle.module)
    public let iconTertiaryAlpha = Color("iconTertiaryAlpha", bundle: Bundle.module)
    public let iconWarningPrimary = CompoundCoreColorTokens.orange900
    public let separatorPrimary = CompoundCoreColorTokens.gray400
    public let separatorSecondary = CompoundCoreColorTokens.gray300
    public let textActionAccent = Color("textActionAccent", bundle: Bundle.module)
    public let textActionPrimary = Color("textActionPrimary", bundle: Bundle.module)
    public let textActionSuccess = CompoundCoreColorTokens.green900
    public let textBadgeAccent = Color("textBadgeAccent", bundle: Bundle.module)
    public let textBadgeCritical = Color("textBadgeCritical", bundle: Bundle.module)
    public let textBadgeDefault = Color("textBadgeDefault", bundle: Bundle.module)
    public let textBadgeInfo = Color("textBadgeInfo", bundle: Bundle.module)
    public let textBadgePrimary = Color("textBadgePrimary", bundle: Bundle.module)
    public let textBadgeSecondary = Color("textBadgeSecondary", bundle: Bundle.module)
    public let textBadgeSuccess = Color("textBadgeSuccess", bundle: Bundle.module)
    public let textBadgeWarning = Color("textBadgeWarning", bundle: Bundle.module)
    public let textCriticalPrimary = Color("textCriticalPrimary", bundle: Bundle.module)
    public let textDecorative1 = Color("textDecorative1", bundle: Bundle.module)
    public let textDecorative2 = Color("textDecorative2", bundle: Bundle.module)
    public let textDecorative3 = Color("textDecorative3", bundle: Bundle.module)
    public let textDecorative4 = Color("textDecorative4", bundle: Bundle.module)
    public let textDecorative5 = Color("textDecorative5", bundle: Bundle.module)
    public let textDecorative6 = Color("textDecorative6", bundle: Bundle.module)
    public let textDisabled = Color("textDisabled", bundle: Bundle.module)
    public let textInfoPrimary = Color("textInfoPrimary", bundle: Bundle.module)
    public let textLinkExternal = Color("textLinkExternal", bundle: Bundle.module)
    public let textOnSolidPrimary = Color("textOnSolidPrimary", bundle: Bundle.module)
    public let textPrimary = Color("textPrimary", bundle: Bundle.module)
    public let textSecondary = Color("textSecondary", bundle: Bundle.module)
    public let textSuccessPrimary = Color("textSuccessPrimary", bundle: Bundle.module)
    public let textWarningPrimary = CompoundCoreColorTokens.orange900
    public init() { }
}
