
//
// CompoundColorTokens.swift
//

import SwiftUI

public class CompoundColorTokens {
    public let bgAccentHovered = CompoundCoreColorTokens.green1000
    public let bgAccentPressed = CompoundCoreColorTokens.green1100
    public let bgAccentRest = CompoundCoreColorTokens.green900
    public let bgAccentSelected = CompoundCoreColorTokens.alphaGreen300
    public let bgAccentSubtle = CompoundCoreColorTokens.green200
    public let bgActionPrimaryDisabled = CompoundCoreColorTokens.gray700
    public let bgActionPrimaryHovered = CompoundCoreColorTokens.gray1200
    public let bgActionPrimaryPressed = CompoundCoreColorTokens.gray1100
    public let bgActionPrimaryRest = CompoundCoreColorTokens.gray1400
    public let bgActionSecondaryHovered = CompoundCoreColorTokens.alphaGray200
    public let bgActionSecondaryPressed = CompoundCoreColorTokens.alphaGray300
    public let bgActionSecondaryRest = CompoundCoreColorTokens.themeBg
    public let bgActionTertiaryHovered = CompoundCoreColorTokens.gray300
    public let bgActionTertiaryRest = CompoundCoreColorTokens.themeBg
    public let bgActionTertiarySelected = CompoundCoreColorTokens.gray400
    public let bgBadgeAccent = Color("bgBadgeAccent", bundle: Bundle.module)
    public let bgBadgeCritical = Color("bgBadgeCritical", bundle: Bundle.module)
    public let bgBadgeDefault = Color("bgBadgeDefault", bundle: Bundle.module)
    public let bgBadgeInfo = Color("bgBadgeInfo", bundle: Bundle.module)
    public let bgBadgePrimary = Color("bgBadgePrimary", bundle: Bundle.module)
    public let bgBadgeSecondary = Color("bgBadgeSecondary", bundle: Bundle.module)
    public let bgBadgeSuccess = Color("bgBadgeSuccess", bundle: Bundle.module)
    public let bgBadgeWarning = Color("bgBadgeWarning", bundle: Bundle.module)
    public let bgCanvasDefault = CompoundCoreColorTokens.themeBg
    public let bgCanvasDefaultLevel1 = Color("bgCanvasDefaultLevel1", bundle: Bundle.module)
    public let bgCanvasDisabled = CompoundCoreColorTokens.gray200
    public let bgCriticalHovered = Color("bgCriticalHovered", bundle: Bundle.module)
    public let bgCriticalPrimary = Color("bgCriticalPrimary", bundle: Bundle.module)
    public let bgCriticalSubtle = Color("bgCriticalSubtle", bundle: Bundle.module)
    public let bgCriticalSubtleHovered = Color("bgCriticalSubtleHovered", bundle: Bundle.module)
    public let bgDecorative1 = CompoundCoreColorTokens.green300
    public let bgDecorative2 = CompoundCoreColorTokens.cyan300
    public let bgDecorative3 = CompoundCoreColorTokens.fuchsia300
    public let bgDecorative4 = CompoundCoreColorTokens.purple300
    public let bgDecorative5 = CompoundCoreColorTokens.pink300
    public let bgDecorative6 = CompoundCoreColorTokens.orange300
    public let bgInfoSubtle = CompoundCoreColorTokens.blue200
    public let bgSubtlePrimary = Color("bgSubtlePrimary", bundle: Bundle.module)
    public let bgSubtleSecondary = Color("bgSubtleSecondary", bundle: Bundle.module)
    public let bgSubtleSecondaryLevel0 = Color("bgSubtleSecondaryLevel0", bundle: Bundle.module)
    public let bgSubtleTertiary = CompoundCoreColorTokens.gray100
    public let bgSuccessHovered = CompoundCoreColorTokens.green1000
    public let bgSuccessPressed = CompoundCoreColorTokens.green1100
    public let bgSuccessRest = CompoundCoreColorTokens.green900
    public let bgSuccessSubtle = CompoundCoreColorTokens.green200
    public let borderAccentPrimary = CompoundCoreColorTokens.green900
    public let borderAccentSubtle = CompoundCoreColorTokens.blue700
    public let borderCriticalHovered = CompoundCoreColorTokens.red1000
    public let borderCriticalPrimary = CompoundCoreColorTokens.red900
    public let borderCriticalSubtle = CompoundCoreColorTokens.red500
    public let borderDisabled = CompoundCoreColorTokens.gray500
    public let borderFocused = CompoundCoreColorTokens.blue500
    public let borderInfoSubtle = CompoundCoreColorTokens.blue700
    public let borderInteractiveHovered = CompoundCoreColorTokens.gray1100
    public let borderInteractivePrimary = CompoundCoreColorTokens.gray800
    public let borderInteractiveSecondary = CompoundCoreColorTokens.gray600
    public let borderSuccessPrimary = CompoundCoreColorTokens.green900
    public let borderSuccessSubtle = CompoundCoreColorTokens.green500
    public let gradientActionStop1 = Color("gradientActionStop1", bundle: Bundle.module)
    public let gradientActionStop2 = Color("gradientActionStop2", bundle: Bundle.module)
    public let gradientActionStop3 = Color("gradientActionStop3", bundle: Bundle.module)
    public let gradientActionStop4 = Color("gradientActionStop4", bundle: Bundle.module)
    public let gradientCriticalStop1 = CompoundCoreColorTokens.red200
    public let gradientCriticalStop2 = CompoundCoreColorTokens.themeBg
    public let gradientInfoStop1 = CompoundCoreColorTokens.blue200
    public let gradientInfoStop2 = CompoundCoreColorTokens.themeBg
    public let gradientSubtleStop1 = CompoundCoreColorTokens.alphaGreen500
    public let gradientSubtleStop2 = CompoundCoreColorTokens.alphaGreen400
    public let gradientSubtleStop3 = CompoundCoreColorTokens.alphaGreen300
    public let gradientSubtleStop4 = CompoundCoreColorTokens.alphaGreen200
    public let gradientSubtleStop5 = CompoundCoreColorTokens.alphaGreen100
    public let gradientSubtleStop6 = CompoundCoreColorTokens.transparent
    public let iconAccentPrimary = CompoundCoreColorTokens.green900
    public let iconAccentTertiary = CompoundCoreColorTokens.green800
    public let iconCriticalPrimary = CompoundCoreColorTokens.red900
    public let iconDisabled = CompoundCoreColorTokens.gray700
    public let iconInfoPrimary = CompoundCoreColorTokens.blue1100
    public let iconOnSolidPrimary = CompoundCoreColorTokens.themeBg
    public let iconPrimary = CompoundCoreColorTokens.gray1400
    public let iconPrimaryAlpha = CompoundCoreColorTokens.alphaGray1400
    public let iconQuaternary = CompoundCoreColorTokens.gray700
    public let iconQuaternaryAlpha = CompoundCoreColorTokens.alphaGray700
    public let iconSecondary = CompoundCoreColorTokens.gray900
    public let iconSecondaryAlpha = CompoundCoreColorTokens.alphaGray900
    public let iconSuccessPrimary = CompoundCoreColorTokens.green900
    public let iconTertiary = CompoundCoreColorTokens.gray800
    public let iconTertiaryAlpha = CompoundCoreColorTokens.alphaGray800
    public let iconWarningPrimary = CompoundCoreColorTokens.orange900
    public let separatorPrimary = CompoundCoreColorTokens.gray400
    public let separatorSecondary = CompoundCoreColorTokens.gray300
    public let textActionAccent = CompoundCoreColorTokens.green900
    public let textActionPrimary = CompoundCoreColorTokens.gray1400
    public let textActionSuccess = CompoundCoreColorTokens.green900
    public let textBadgeAccent = CompoundCoreColorTokens.green1100
    public let textBadgeInfo = CompoundCoreColorTokens.blue1100
    public let textCriticalPrimary = CompoundCoreColorTokens.red900
    public let textDecorative1 = CompoundCoreColorTokens.lime1100
    public let textDecorative2 = CompoundCoreColorTokens.cyan1100
    public let textDecorative3 = CompoundCoreColorTokens.fuchsia1100
    public let textDecorative4 = CompoundCoreColorTokens.purple1100
    public let textDecorative5 = CompoundCoreColorTokens.pink1100
    public let textDecorative6 = CompoundCoreColorTokens.orange1100
    public let textDisabled = CompoundCoreColorTokens.gray800
    public let textInfoPrimary = CompoundCoreColorTokens.blue1100
    public let textLinkExternal = CompoundCoreColorTokens.blue1100
    public let textOnSolidPrimary = CompoundCoreColorTokens.themeBg
    public let textPrimary = CompoundCoreColorTokens.gray1400
    public let textSecondary = CompoundCoreColorTokens.gray900
    public let textSuccessPrimary = CompoundCoreColorTokens.green900
    public let textWarningPrimary = CompoundCoreColorTokens.orange900
    public init() { }
}
